package com.gohgai.thaifoodtalker;

import android.content.res.Resources;
import android.media.AudioManager;
import android.os.Bundle;
import android.support.design.widget.NavigationView;
import android.support.v4.app.Fragment;
import android.support.v4.view.GravityCompat;
import android.support.v4.widget.DrawerLayout;
import android.support.v7.app.ActionBarDrawerToggle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.Menu;
import android.view.MenuItem;

import java.util.ArrayList;

/**
 * A lot of this coding is generated by Android Studio
 * Some add on is created by Rattanawalee(Rain) Surasorn 4/1/2016
 */
public class MainActivity extends AppCompatActivity
        implements NavigationView.OnNavigationItemSelectedListener {


    Toolbar toolbar = null;
    NavigationView navigationView = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        //create tool bar
        toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        Resources res = getResources();

        ////////set homepage fragment to display //////////////
         FoodListFragment fragment = FoodListFragment.getFragmentInstance(
                "Quick Menu",
                res.getStringArray(R.array.recommended_thaifood_title),
                res.getStringArray(R.array.recommended_thaifood_pronunciations),
                AudiosArrays.HOME_AUDIOS,
                res.getStringArray(R.array.recommended_thaifood_thai),
                ImagesArrays.HOME_IMAGES,
                res.getStringArray(R.array.homepage_web_credits)
        );

        android.support.v4.app.FragmentTransaction fragmentTransaction =
                this.getSupportFragmentManager().beginTransaction();
        fragmentTransaction.replace(R.id.main_fragmentContainer, fragment);
        fragmentTransaction.commit();
        /////////////////////////////////////////////

        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        ActionBarDrawerToggle toggle = new ActionBarDrawerToggle(
                this, drawer, toolbar, R.string.navigation_drawer_open,
                R.string.navigation_drawer_close);
        drawer.setDrawerListener(toggle);
        toggle.syncState();

        navigationView = (NavigationView) findViewById(R.id.nav_view);
        navigationView.setNavigationItemSelectedListener(this);

        //Listen to the phone's hardware volume's control
        setVolumeControlStream(AudioManager.STREAM_MUSIC);

    }

    @Override
    public void onBackPressed() {
        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        if (drawer.isDrawerOpen(GravityCompat.START)) {
            drawer.closeDrawer(GravityCompat.START);
        } else {
            super.onBackPressed();
        }
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    @SuppressWarnings("StatementWithEmptyBody")
    @Override
    public boolean onNavigationItemSelected(MenuItem item) {
        // Handle navigation view item clicks here.
        int id = item.getItemId();
        android.support.v4.app.FragmentTransaction fragmentTransaction =
                this.getSupportFragmentManager().beginTransaction();

        Resources res = getResources();

        Fragment fragment = null;

        if (id == R.id.nav_home) {

           // HomeFragment homeFragment = new HomeFragment();
           // fragmentTransaction.replace(R.id.main_fragmentContainer, homeFragment);

            fragment = FoodListFragment.getFragmentInstance(
                    "Quick Menu",
                    res.getStringArray(R.array.recommended_thaifood_title),
                    res.getStringArray(R.array.recommended_thaifood_pronunciations),
                    AudiosArrays.HOME_AUDIOS,
                    res.getStringArray(R.array.recommended_thaifood_thai),
                    ImagesArrays.HOME_IMAGES,
                    res.getStringArray(R.array.homepage_web_credits)
            );
            fragmentTransaction.replace(R.id.main_fragmentContainer, fragment);

        } else if (id == R.id.nav_seating) {


            fragment = NoImagesFragment.getFragmentInstance(
                    "Asking for a Table",
                    res.getStringArray(R.array.seating_titles),
                    res.getStringArray(R.array.seating_pronunciations),
                    AudiosArrays.SEATING_AUDIOS,
                    res.getStringArray(R.array.seating_thais)
            );
            fragmentTransaction.replace(R.id.main_fragmentContainer, fragment);

        } else if (id == R.id.nav_restroom) {

            fragment = NoImagesFragment.getFragmentInstance(
                   "Asking for a Restroom",
                    res.getStringArray(R.array.restroom_titles),
                    res.getStringArray(R.array.restroom_pronunciation),
                    AudiosArrays.RESTROOM_AUDIOS,
                    res.getStringArray(R.array.restroom_thais)
            );

            fragmentTransaction.replace(R.id.main_fragmentContainer,fragment);

        } else if (id == R.id.nav_bill) {

            fragment = NoImagesFragment.getFragmentInstance(
                    "Asking for a Bill",
                    res.getStringArray(R.array.bill_titles),
                    res.getStringArray(R.array.bill_pronunciations),
                    AudiosArrays.BILL_AUDIOS,
                    res.getStringArray(R.array.bill_thais)

            );
            fragmentTransaction.replace(R.id.main_fragmentContainer, fragment);

        }else if(id == R.id.nav_allergies){

            fragment = NoImagesFragment.getFragmentInstance(
                    "Allergies",
                    res.getStringArray(R.array.allergies_titles),
                    res.getStringArray(R.array.allergies_pronunciations),
                    AudiosArrays.ALLERGY_AUDIOS,
                    res.getStringArray(R.array.allergies_thais)

            );
            fragmentTransaction.replace(R.id.main_fragmentContainer, fragment);

        } else if (id == R.id.nav_share) {

        } else if (id == R.id.nav_send) {

        }else if(id == R.id.nav_help){

            HelpFragment helpFragment = new HelpFragment();
            fragmentTransaction.replace(R.id.main_fragmentContainer, helpFragment);

        }else if (id == R.id.nav_protien_choices){

            fragment = NoImagesFragment.getFragmentInstance(
                    "Protein Choices",
                    res.getStringArray(R.array.animals_titles),
                    res.getStringArray(R.array.animals_pronunciations),
                    AudiosArrays.PROTIEN_AUDIOS,
                    res.getStringArray(R.array.animals_thais)
            );
            fragmentTransaction.replace(R.id.main_fragmentContainer, fragment);
        }else if (id == R.id.nav_grilling){

            fragment = FoodListFragment.getFragmentInstance(
                    "Grilling",
                    res.getStringArray(R.array.grilling_titles),
                    res.getStringArray(R.array.grilling_pronunciations),
                    AudiosArrays.GRILLING_AUDIOS,
                    res.getStringArray(R.array.grilling_thais),
                    ImagesArrays.GRILLED_IMAGES,
                    res.getStringArray(R.array.grilling_web_credits)
            );
            fragmentTransaction.replace(R.id.main_fragmentContainer, fragment);
        }

        fragmentTransaction.commit();
        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        drawer.closeDrawer(GravityCompat.START);
        return true;
    }

}
